neat:
  add_node: 0.99
  add_edge: 0.7

logs:
  log_dir: './logs'

jax:
  PRNGKey: 30

training:
  num_epochs: 1
  generations: 10
  visualize_epochs: False
  batch_size: 32
  lr: 0.1

network:
  num_output: 3
  num_layers: [1]
  num_inputs: 4 

dataset:
  dataset_type: "iris"
  