neat:
  add_node: 0.99
  add_layer: 0.09
  remove_node: 0.2
  remove_layer: 0.2

logs:
  log_dir: './logs'

jax:
  PRNGKey: 30

training:
  num_epochs: 300
  generations: 20
  visualize_epochs: False
  batch_size: 32
  lr: 0.1

network:
  num_output: 10
  num_layers: [1]
  num_inputs: 784 #MNIST is 28 * 28 images

dataset:
  dataset_type: "mnist"

utils:
  draw_graph: False
  